export type Platform = {
	platform_code: number;
	trackName: string;
	trackCode: string;
	next: string[]; // next stops (gtfs stop id) for the exitSide to be correct; else swap left and right
	exitSide: "left" | "right" | "both";
};

export type PlatformData = {
	[gtfs_stop_id: string]: Platform[];
};

export const platformData: PlatformData = {
	place_romsta: [
		{
			platform_code: 2,
			trackName: "Roma Street P2",
			trackCode: "RSTP2",
			next: ["place_censta"],
			exitSide: "right",
		},
		{
			platform_code: 3,
			trackName: "Roma Street P3",
			trackCode: "RSTP3",
			next: ["place_censta"],
			exitSide: "left",
		},
		{
			platform_code: 4,
			trackName: "Roma Street P4",
			trackCode: "RSTP4",
			next: ["place_censta"],
			exitSide: "left",
		},
		{
			platform_code: 5,
			trackName: "Roma Street P5",
			trackCode: "RSTP5",
			next: ["place_censta"],
			exitSide: "right",
		},
		{
			platform_code: 6,
			trackName: "Roma Street P6",
			trackCode: "RSTP6",
			next: ["place_censta"],
			exitSide: "left",
		},
		{
			platform_code: 7,
			trackName: "Roma Street P7",
			trackCode: "RSTP7",
			next: ["place_censta"],
			exitSide: "right",
		},
		{
			platform_code: 8,
			trackName: "Roma Street P8",
			trackCode: "RSTP8",
			next: ["place_censta"],
			exitSide: "left",
		},
		{
			platform_code: 9,
			trackName: "Roma Street P9",
			trackCode: "RSTP9",
			next: ["place_censta"],
			exitSide: "right",
		},
		{
			platform_code: 10,
			trackName: "Roma Street P0",
			trackCode: "RSTP0",
			next: ["place_censta"],
			exitSide: "left",
		},
	],
	place_censta: [
		{
			platform_code: 1,
			trackName: "Up Suburban - Central Line",
			trackCode: "USC",
			next: ["place_romsta"],
			exitSide: "right",
		},
		{
			platform_code: 2,
			trackName: "Central P2",
			trackCode: "CENP2",
			next: ["place_romsta"],
			exitSide: "left",
		},
		{
			platform_code: 3,
			trackName: "Down Suburban - Central Line",
			trackCode: "DSC",
			next: ["place_forsta"],
			exitSide: "left",
		},
		{
			platform_code: 4,
			trackName: "Central P4",
			trackCode: "CENP4",
			next: ["place_forsta"],
			exitSide: "right",
		},
		{
			platform_code: 5,
			trackName: "Up Main - Central Line",
			trackCode: "UMC",
			next: ["place_romsta"],
			exitSide: "right",
		},
		{
			platform_code: 6,
			trackName: "Down Main - Central Line",
			trackCode: "DMC",
			next: ["place_forsta"],
			exitSide: "left",
		},
	],
	place_forsta: [
		{
			platform_code: 1,
			trackName: "Up Suburban - Central Line",
			trackCode: "USC",
			next: ["place_censta"],
			exitSide: "right",
		},
		{
			platform_code: 2,
			trackName: "Down Suburban - Central Line",
			trackCode: "DSC",
			next: ["place_bowsta"],
			exitSide: "right",
		},
		{
			platform_code: 3,
			trackName: "Up Main - Central Line",
			trackCode: "UMC",
			next: ["place_censta"],
			exitSide: "right",
		},
		{
			platform_code: 4,
			trackName: "Down Main - Central Line",
			trackCode: "DMC",
			next: ["place_bowsta"],
			exitSide: "right",
		},
	],
	place_bowsta: [
		{
			platform_code: 1,
			trackName: "Up Suburban - Central Line",
			trackCode: "USC",
			next: ["place_forsta"],
			exitSide: "right",
		},
		{
			platform_code: 2,
			trackName: "Down Suburban - Central Line",
			trackCode: "DSC",
			next: ["place_albsta", "place_wilsta"],
			exitSide: "right",
		},
		{
			platform_code: 3,
			trackName: "Up Main - Central Line",
			trackCode: "UMC",
			next: ["place_forsta"],
			exitSide: "right",
		},
		{
			platform_code: 4,
			trackName: "Down Main - Central Line",
			trackCode: "DMC",
			next: ["place_albsta", "place_wilsta"],
			exitSide: "right",
		},
	],
	place_albsta: [
		{
			platform_code: 1,
			trackName: "Up Suburban - Central Line",
			trackCode: "USC",
			next: ["place_bowsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down Suburban - Central Line",
			trackCode: "DSC",
			next: ["place_wolsta"],
			exitSide: "left",
		},
		{
			platform_code: 3,
			trackName: "Up Main - Central Line",
			trackCode: "UMC",
			next: ["place_bowsta"],
			exitSide: "left",
		},
		{
			platform_code: 4,
			trackName: "Down Main - Central Line",
			trackCode: "DMC",
			next: ["place_wolsta"],
			exitSide: "left",
		},
	],
	place_wolsta: [
		{
			platform_code: 1,
			trackName: "Up Suburban - Central Line",
			trackCode: "USC",
			next: ["place_albsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down Suburban - Central Line",
			trackCode: "DSC",
			next: ["place_egjsta"],
			exitSide: "left",
		},
		{
			platform_code: 3,
			trackName: "Up Main - Central Line",
			trackCode: "UMC",
			next: ["place_albsta"],
			exitSide: "left",
		},
		{
			platform_code: 4,
			trackName: "Down Main - Central Line",
			trackCode: "DMC",
			next: ["place_egjsta"],
			exitSide: "left",
		},
	],
	place_egjsta: [
		{
			platform_code: 1,
			trackName: "Up Suburban - Central Line",
			trackCode: "USC",
			next: ["place_wolsta"],
			exitSide: "right",
		},
		{
			platform_code: 2,
			trackName: "Down Suburban - Central Line",
			trackCode: "DSC",
			next: ["place_clasta", "place_intsta", "place_tomsta"],
			exitSide: "right",
		},
		{
			platform_code: 3,
			trackName: "Up Main - Central Line",
			trackCode: "UMC",
			next: ["place_wolsta"],
			exitSide: "right",
		},
		{
			platform_code: 4,
			trackName: "Down Main - Central Line",
			trackCode: "DMC",
			next: ["place_clasta", "place_intsta", "place_tomsta"],
			exitSide: "right",
		},
	],
	place_clasta: [
		{
			platform_code: 1,
			trackName: "Doomben Line",
			trackCode: "DBL",
			next: ["place_hensta"],
			exitSide: "left",
		},
	],
	place_hensta: [
		{
			platform_code: 1,
			trackName: "Doomben Line",
			trackCode: "DBL",
			next: ["place_ascsta"],
			exitSide: "right",
		},
	],
	place_ascsta: [
		{
			platform_code: 1,
			trackName: "Doomben Line",
			trackCode: "DBL",
			next: ["place_dbnsta"],
			exitSide: "right",
		},
	],
	place_dbnsta: [
		{
			platform_code: 1,
			trackName: "Doomben P1",
			trackCode: "DBNP1",
			next: ["place_ascsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Doomben P2",
			trackCode: "DBNP2",
			next: ["place_ascsta"],
			exitSide: "right",
		},
	],
	place_intsta: [
		{
			platform_code: 1,
			trackName: "Track 1 - Airport Line",
			trackCode: "APL1",
			next: ["place_domsta"],
			exitSide: "right",
		},
		{
			platform_code: 2,
			trackName: "Track 2 - Airport Line",
			trackCode: "APL2",
			next: ["place_domsta"],
			exitSide: "left",
		},
	],
	place_domsta: [
		{
			platform_code: 1,
			trackName: "Track 1 - Airport Line",
			trackCode: "APL1",
			next: ["place_intsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Track 2 - Airport Line",
			trackCode: "APL2",
			next: ["place_intsta"],
			exitSide: "right",
		},
	],
	place_tomsta: [
		{
			platform_code: 1,
			trackName: "Up Suburban - Central Line",
			trackCode: "USC",
			next: ["place_egjsta"],
			exitSide: "right",
		},
		{
			platform_code: 2,
			trackName: "Down Suburban - Central Line",
			trackCode: "DSC",
			next: ["place_nunsta"],
			exitSide: "right",
		},
		{
			platform_code: 3,
			trackName: "Up Main - Central Line",
			trackCode: "UMC",
			next: ["place_egjsta"],
			exitSide: "right",
		},
		{
			platform_code: 4,
			trackName: "Down Main - Central Line",
			trackCode: "DMC",
			next: ["place_nunsta"],
			exitSide: "right",
		},
	],
	place_nunsta: [
		{
			platform_code: 1,
			trackName: "Up Suburban - Central Line",
			trackCode: "USC",
			next: ["place_tomsta"],
			exitSide: "right",
		},
		{
			platform_code: 2,
			trackName: "Down Suburban - Central Line",
			trackCode: "DSC",
			next: ["place_norsta"],
			exitSide: "right",
		},
		{
			platform_code: 3,
			trackName: "Up Main - Central Line",
			trackCode: "UMC",
			next: ["place_tomsta"],
			exitSide: "right",
		},
		{
			platform_code: 4,
			trackName: "Down Main - Central Line",
			trackCode: "DMC",
			next: ["place_norsta"],
			exitSide: "right",
		},
	],
	place_norsta: [
		{
			platform_code: 1,
			trackName: "Up Suburban - Central Line",
			trackCode: "USC",
			next: ["place_nunsta"],
			exitSide: "right",
		},
		{
			platform_code: 2,
			trackName: "Down Suburban - Central Line",
			trackCode: "DSC",
			next: ["place_virsta", "place_binsta"],
			exitSide: "right",
		},
		{
			platform_code: 3,
			trackName: "Up Main - Central Line",
			trackCode: "UMC",
			next: ["place_nunsta"],
			exitSide: "right",
		},
		{
			platform_code: 4,
			trackName: "Down Main - Central Line",
			trackCode: "DMC",
			next: ["place_virsta", "place_binsta"],
			exitSide: "right",
		},
	],
	place_binsta: [
		{
			platform_code: 1,
			trackName: "Up - Shorncliffe Line",
			trackCode: "USH",
			next: ["place_norsta"],
			exitSide: "right",
		},
		{
			platform_code: 2,
			trackName: "Down - Shorncliffe Line",
			trackCode: "DSH",
			next: ["place_baysta"],
			exitSide: "right",
		},
	],
	place_baysta: [
		{
			platform_code: 1,
			trackName: "Up - Shorncliffe Line",
			trackCode: "USH",
			next: ["place_binsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down - Shorncliffe Line",
			trackCode: "DSH",
			next: ["place_nudsta"],
			exitSide: "left",
		},
	],
	place_nudsta: [
		{
			platform_code: 1,
			trackName: "Up - Shorncliffe Line",
			trackCode: "USH",
			next: ["place_baysta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down - Shorncliffe Line",
			trackCode: "DSH",
			next: ["place_bdlsta"],
			exitSide: "left",
		},
	],
	place_bdlsta: [
		{
			platform_code: 1,
			trackName: "Up - Shorncliffe Line",
			trackCode: "USH",
			next: ["place_nudsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down - Shorncliffe Line",
			trackCode: "DSH",
			next: ["place_nobsta"],
			exitSide: "left",
		},
	],
	place_nobsta: [
		{
			platform_code: 1,
			trackName: "Up - Shorncliffe Line",
			trackCode: "USH",
			next: ["place_bdlsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down - Shorncliffe Line",
			trackCode: "DSH",
			next: ["place_deasta"],
			exitSide: "left",
		},
	],
	place_deasta: [
		{
			platform_code: 1,
			trackName: "Up - Shorncliffe Line",
			trackCode: "USH",
			next: ["place_nobsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down - Shorncliffe Line",
			trackCode: "DSH",
			next: ["place_sgtsta"],
			exitSide: "left",
		},
	],
	place_sgtsta: [
		{
			platform_code: 1,
			trackName: "Down - Shorncliffe Line",
			trackCode: "DSH",
			next: ["place_shnsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Up - Shorncliffe Line",
			trackCode: "USH",
			next: ["place_deasta"],
			exitSide: "left",
		},
	],
	place_shnsta: [
		{
			platform_code: 1,
			trackName: "Shorncliffe P1",
			trackCode: "SHNP1",
			next: ["place_sgtsta"],
			exitSide: "right",
		},
	],
	place_virsta: [
		{
			platform_code: 1,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_norsta"],
			exitSide: "right",
		},
		{
			platform_code: 2,
			trackName: "Middle - Northern Line",
			trackCode: "MTN",
			next: ["place_snssta"],
			exitSide: "right",
		},
		{
			platform_code: 3,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_snssta"],
			exitSide: "left",
		},
	],
	place_snssta: [
		{
			platform_code: 1,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_virsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Middle - Northern Line",
			trackCode: "MTN",
			next: ["place_geesta"],
			exitSide: "left",
		},
		{
			platform_code: 3,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_geesta"],
			exitSide: "right",
		},
	],
	place_geesta: [
		{
			platform_code: 1,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_snssta"],
			exitSide: "right",
		},
		{
			platform_code: 2,
			trackName: "Middle - Northern Line",
			trackCode: "MTN",
			next: ["place_zllsta"],
			exitSide: "right",
		},
		{
			platform_code: 3,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_zllsta"],
			exitSide: "left",
		},
	],
	place_zllsta: [
		{
			platform_code: 1,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_geesta"],
			exitSide: "right",
		},
		{
			platform_code: 2,
			trackName: "Middle - Northern Line",
			trackCode: "MTN",
			next: ["place_cassta"],
			exitSide: "right",
		},
		{
			platform_code: 3,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_cassta"],
			exitSide: "left",
		},
	],
	place_cassta: [
		{
			platform_code: 1,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_zllsta"],
			exitSide: "right",
		},
		{
			platform_code: 2,
			trackName: "Middle - Northern Line",
			trackCode: "MTN",
			next: ["place_balsta"],
			exitSide: "right",
		},
		{
			platform_code: 3,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_balsta"],
			exitSide: "left",
		},
	],
	place_balsta: [
		{
			platform_code: 1,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_cassta"],
			exitSide: "right",
		},
		{
			platform_code: 2,
			trackName: "Middle - Northern Line",
			trackCode: "MTN",
			next: ["place_strsta"],
			exitSide: "right",
		},
		{
			platform_code: 3,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_strsta"],
			exitSide: "left",
		},
	],
	place_strsta: [
		{
			platform_code: 1,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_balsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Middle - Northern Line",
			trackCode: "MTN",
			next: ["place_brasta"],
			exitSide: "left",
		},
		{
			platform_code: 3,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_brasta"],
			exitSide: "right",
		},
	],
	place_brasta: [
		{
			platform_code: 1,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_strsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Middle - Northern Line",
			trackCode: "MTN",
			next: ["place_petsta"],
			exitSide: "left",
		},
		{
			platform_code: 3,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_petsta"],
			exitSide: "right",
		},
	],
	place_petsta: [
		{
			platform_code: 1,
			trackName: "Petrie P1",
			trackCode: "PETP1",
			next: ["place_daksta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Petrie P2",
			trackCode: "PETP2",
			next: ["place_daksta"],
			exitSide: "right",
		},
		{
			platform_code: 3,
			trackName: "Petrie P3",
			trackCode: "PETP3",
			next: ["place_kalsta"],
			exitSide: "left",
		},
		{
			platform_code: 4,
			trackName: "Petrie P4",
			trackCode: "PETP4",
			next: ["place_brasta"],
			exitSide: "left",
		},
		{
			platform_code: 5,
			trackName: "Petrie P5",
			trackCode: "PETP5",
			next: ["place_brasta"],
			exitSide: "right",
		},
	],
	place_kalsta: [
		{
			platform_code: 1,
			trackName: "Up - Redcliffe Line",
			trackCode: "URL",
			next: ["place_petsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down - Redcliffe Line",
			trackCode: "DRL",
			next: ["place_mudsta"],
			exitSide: "left",
		},
	],
	place_mudsta: [
		{
			platform_code: 1,
			trackName: "Up - Redcliffe Line",
			trackCode: "URL",
			next: ["place_kalsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down - Redcliffe Line",
			trackCode: "DRL",
			next: ["place_mahsta"],
			exitSide: "left",
		},
	],
	place_mahsta: [
		{
			platform_code: 1,
			trackName: "Up - Redcliffe Line",
			trackCode: "URL",
			next: ["place_mudsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down - Redcliffe Line",
			trackCode: "DRL",
			next: ["place_mhesta"],
			exitSide: "left",
		},
	],
	place_mhesta: [
		{
			platform_code: 1,
			trackName: "Up - Redcliffe Line",
			trackCode: "URL",
			next: ["place_mahsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down - Redcliffe Line",
			trackCode: "DRL",
			next: ["place_rotsta"],
			exitSide: "left",
		},
	],
	place_rotsta: [
		{
			platform_code: 1,
			trackName: "Down - Redcliffe Line",
			trackCode: "DRL",
			next: ["place_kprsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Up - Redcliffe Line",
			trackCode: "URL",
			next: ["place_mhesta"],
			exitSide: "left",
		},
	],
	place_kprsta: [
		{
			platform_code: 1,
			trackName: "Kippa-Ring P1",
			trackCode: "KPRP1",
			next: ["place_rotsta"],
			exitSide: "right",
		},
		{
			platform_code: 2,
			trackName: "Kippa-Ring P2",
			trackCode: "KPRP2",
			next: ["place_rotsta"],
			exitSide: "left",
		},
	],
	place_daksta: [
		{
			platform_code: 1,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_petsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_narsta"],
			exitSide: "right",
		},
	],
	place_narsta: [
		{
			platform_code: 1,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_daksta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Middle Track - Northern Line",
			trackCode: "DMN",
			next: ["place_bursta"],
			exitSide: "left",
		},
		{
			platform_code: 3,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_bursta"],
			exitSide: "left",
		},
	],
	place_bursta: [
		{
			platform_code: 1,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_narsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_myesta"],
			exitSide: "left",
		},
	],
	place_myesta: [
		{
			platform_code: 1,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_bursta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_cabsta"],
			exitSide: "left",
		},
	],
	place_cabsta: [
		{
			platform_code: 1,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_elmsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_myesta"],
			exitSide: "left",
		},
		{
			platform_code: 3,
			trackName: "Caboolture P3",
			trackCode: "CABP3",
			next: ["place_myesta"],
			exitSide: "left",
		},
	],
	place_elmsta: [
		{
			platform_code: 1,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_cabsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_bbrsta"],
			exitSide: "left",
		},
	],
	place_bbrsta: [
		{
			platform_code: 1,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_elmsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_gmtsta"],
			exitSide: "left",
		},
	],
	place_gmtsta: [
		{
			platform_code: 1,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_bbrsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_bwrsta"],
			exitSide: "left",
		},
	],
	place_bwrsta: [
		{
			platform_code: 1,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_gmtsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_lansta"],
			exitSide: "left",
		},
	],
	place_lansta: [
		{
			platform_code: 1,
			trackName: "Down Main - Northern Line",
			trackCode: "DMN",
			next: ["place_molsta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Up Main - Northern Line",
			trackCode: "UMN",
			next: ["place_bwrsta"],
			exitSide: "left",
		},
	],
	place_molsta: [
		{
			platform_code: 1,
			trackName: "Mooloolah P1",
			trackCode: "MOLP1",
			next: ["place_lansta"],
			exitSide: "left",
		},
	],
	place_eudsta: [
		{
			platform_code: 1,
			trackName: "Eudlo P1",
			trackCode: "EUDP1",
			next: ["place_molsta"],
			exitSide: "left",
		},
	],
	place_palsta: [
		{
			platform_code: 1,
			trackName: "Palmwoods P1",
			trackCode: "PALP1",
			next: ["place_eudsta"],
			exitSide: "left",
		},
	],
	place_wbysta: [
		{
			platform_code: 1,
			trackName: "Woombye P1",
			trackCode: "WBYRP1",
			next: ["place_palsta"],
			exitSide: "left",
		},
	],
	place_nambsta: [
		{
			platform_code: 1,
			trackName: "Nambour P1",
			trackCode: "NAMBP1",
			next: ["place_wbysta"],
			exitSide: "left",
		},
		{
			platform_code: 2,
			trackName: "Nambour P2",
			trackCode: "NAMBP2",
			next: ["place_wbysta"],
			exitSide: "right",
		},
	],
	place_yansta: [
		{
			platform_code: 1,
			trackName: "Yandina P1",
			trackCode: "YANDP1",
			next: ["place_nambsta"],
			exitSide: "right",
		},
	],
	place_eumsta: [
		{
			platform_code: 1,
			trackName: "Eumundi P1",
			trackCode: "EUMP1",
			next: ["place_yansta"],
			exitSide: "right",
		},
	],
	place_crysta: [
		{
			platform_code: 1,
			trackName: "Cooroy P1",
			trackCode: "COOP1",
			next: ["place_eumsta"],
			exitSide: "left",
		},
	],
    place_pomsta: [
        {
            platform_code: 1,
            trackName: "Pomona P1",
            trackCode: "POMP1",
            next: ["place_crysta"],
            exitSide: "left",
        },
    ],
    place_crnsta: [
        {
            platform_code: 1,
            trackName: "Cooran P1",
            trackCode: "CRNP1",
            next: ["place_pomsta"],
            exitSide: "left",
        },
    ],
    place_trvsta: [
        {
            platform_code: 1,
            trackName: "Traveston P1",
            trackCode: "TRVP1",
            next: ["place_crnsta"],
            exitSide: "left",
        },
    ],
    place_gymsta: [
        {
            platform_code: 1,
            trackName: "Gympie North P1",
            trackCode: "GYMP1",
            next: ["place_trvsta"],
            exitSide: "left",
        },
    ]
    /*
        TODO:
        - Ferny Grove
        - Cleveland
        - Beenleigh / Gold Coast
        - Ipswich / Rosewood
        - Springfield
     */
};

export default platformData;
